---
namespace: "technotim"
description: "k3s"
name: "k3s"
version: "1.24.11"
readme: "README.md"
authors:
  - "Techno Tim <insert your links here>"
dependencies:
  ansible.utils: ">=1.5"
  community.general: ">=6.5.0"
  ansible.posix: ">=1.5"
  kubernetes.core: ">=2.4"
license:
  - "MIT"
tags:
  - demo
  - collection
repository: "https://github.com/techno-tim/k3s-ansible/"
